### ISSUE TITLE
[Start Mini Project] Train LSTM Model for Hand Gesture Recognition

### ISSUE THREAD

**Issue by updaun** [updaun/HandGestureRecognition#1]
### What
- 손동작을 인식하는 모델을 학습시켜봅시다.
- 본인만의 LSTM 모델을 제작해봅시다.

### Why?
- mediapipe 사용하기
- lstm 이해하기
- 학습 성능 개선을 위한 추가 방안 구상하기

### 참고 링크
- https://youtu.be/eHxDWhtbRCk

### Todo
- [ ] #2
- [ ] 사용자 매뉴얼 제작
- [ ] 깃허브 사용자 추가
- [ ] 추가 미션 제작
